services:
  portfolio-frontend:
    build: .
    ports:
      - "3000:80"
    image: portfolio-frontend
    container_name: portfolio-frontend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    external: true
