apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "portfolio.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "portfolio.name" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "portfolio.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "portfolio.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
