apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "portfolio.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "portfolio.name" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "portfolio.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ template "portfolio.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
