apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "portfolio.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "portfolio.name" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "portfolio.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "portfolio.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          resources:
            requests:
              cpu: "{{ .Values.frontend.resources.requests.cpu }}"
              memory: "{{ .Values.frontend.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.frontend.resources.limits.cpu }}"
              memory: "{{ .Values.frontend.resources.limits.memory }}"
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.readinessProbe.httpGet.path }}
              port: {{ .Values.frontend.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
