apiVersion: v1
kind: Service
metadata:
  name: {{ template "portfolio.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "portfolio.name" . }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}
  type: ClusterIP
